apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: repls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: deepanshumishra2004/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: NEXT_PUBLIC_API_URL
              value: "http://api.127.0.0.1.nip.io"
