apiVersion: v1
kind: ServiceAccount
metadata:
  name: repl-manager-sa
  namespace: repls

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: repl-manager-role
  namespace: repls
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: repl-manager-rolebinding
  namespace: repls
subjects:
  - kind: ServiceAccount
    name: repl-manager-sa
    namespace: repls
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: repl-manager-role