apiVersion: v1
kind: Secret
metadata:
  name: repl-runtime-secrets
  namespace: repls
type: Opaque
stringData:
  S3_BUCKET: "change-me"
  AWS_REGION: "ap-south-1"
  REDIS_URL: "redis://redis.repls.svc.cluster.local:6379"
  AWS_ACCESS_KEY_ID: "change-me"
  AWS_SECRET_ACCESS_KEY: "change-me"
  JWT_SECRET: "change-me"
