apiVerion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app
type: Opaque
stringData:
  DATABASE_URL:           "postgresql://neondb_owner:npg_YyEzIovOWD24@ep-winter-queen-a14pmzws-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  REDIS_URL:              "redis://redis-service.data:6379"
  JWT_SECRET:             "deepV1"
  STRIPE_SECRET_KEY:      "sk_live_..."
  STRIPE_WEBHOOK_SECRET:  "whsec_..."
  S3_BUCKET:              "your-bucket-name"
  AWS_REGION:             "us-east-1"